### ISSUE TITLE
Push new Docker image

### ISSUE THREAD

**Issue by MiklerGM** [DenisCarriere/mbtiles-server#10]
Would you mind to update the image on docker hub?

Thanks

**Comment by DenisCarriere** [comment]
Built new image =>

https://cloud.docker.com/repository/docker/deniscarriere/mbtiles-server

**Comment by MiklerGM** [comment]
@DenisCarriere I guess to rebuild an image I should've been logged in your account ;-)

Can I ask you to build a new docker image again, as there are some new commits
