### ISSUE TITLE
Make App able to add Key Cert files

### ISSUE THREAD

**Issue by chpicone** [DenisCarriere/mbtiles-server#21]
If we specify HTTPS as protocol we can't specify the .key and .cert certification files.
I suggest to add the following options:

> --key <path to the .key file>
> --cert <path to the .cert file>

In the source code where we make the app listening to the specified port we have to set this option object:
```
let options = {
    key:  fs.readFileSync('<file>.key',  'utf8'),
    cert: fs.readFileSync('<file>.cert', 'utf8')
};
```
Generally I use creteServer method on http or https object and in the 2nd case (https) I pass this object option as first parameter (the 2nd is the App instance).

**Comment by DenisCarriere** [comment]
👍 great stuff

Merged and published new release
