### ISSUE TITLE
Incorrect variables in dockerfile

### ISSUE THREAD

**Issue by chpicone** [DenisCarriere/mbtiles-server#24]
Dockerfile contains incorrect variable without the prefix "MBTILES_SERVER_".
The container so start always incorrectly with the default parameters values:

`ENV CACHE='/root/mbtiles'`
instead of
`ENV MBTILES_SERVER_CACHE='/root/mbtiles'`

**Comment by DenisCarriere** [comment]
FIxed in https://github.com/DenisCarriere/mbtiles-server/pull/25
